spring:
  application:
    name: SpringCafe
  datasource:
    url: jdbc:mysql://localhost:3306/springCafe
    username: springCafe
    password: springCafe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      show-sql: true
  server:
    port: 8080